apiVersion: v1
kind: Service
metadata:
  labels:
    service: certbot
  name: certbot
spec:
  ports:
    - name: certbot
      port: 80
      targetPort: 80
      protocol: TCP
    - name: certbot-ssl
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    service: certbot
status:
  loadBalancer: {}

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot
spec:
  schedule: "0 0 15 * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      completions: 1
      template:
        metadata:
          labels:
            network/go-live-default: "true"
            service: certbot
        spec:
          containers:
            - image: certbot
              name: certbot
              imagePullPolicy: Never
              command:
                - /bin/sh
                - -c
                - sleep 9999
              stdin: true
              tty: true
              ports:
                - name: web
                  containerPort: 80
                  protocol: TCP
              volumeMounts:
                - mountPath: {{ .Values.mounts.letsencrypt.container.root }}
                  name: certbot-hostpathroot
                - mountPath: {{ .Values.mounts.letsencrypt.container.certs }}
                  name: certbot-hostpathcerts
          hostname: certbot
          restartPolicy: OnFailure
          volumes:
            - hostPath:
                path: {{ .Values.mounts.letsencrypt.host.root }}
                type: Directory
              name: certbot-hostpathroot
            - hostPath:
                path: {{ .Values.mounts.letsencrypt.host.certs }}
                type: Directory
              name: certbot-hostpathcerts
status: {}
