apiVersion: v1
kind: Service
metadata:
  labels:
    service: certbot
  name: certbot
spec:
  ports:
    - name: "9999"
      port: 9999
      targetPort: 9999
  selector:
    service: certbot
status:
  loadBalancer: {}
