apiVersion: apps/v1
kind: Deployment
metadata:
  creationTimestamp: null
  labels:
    service: certbot
  name: certbot
spec:
  replicas: 1
  selector:
    matchLabels:
      service: certbot
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/go-live-default: "true"
        service: certbot
    spec:
      containers:
        - image: certbot
          name: certbot
          imagePullPolicy: Never
          ports:
            - containerPort: 9999
          resources: {}
          stdin: true
          tty: true
          volumeMounts:
            - mountPath: {{ .Values.mounts.letsencrypt.container.root }}
              name: certbot-hostpathroot
            - mountPath: {{ .Values.mounts.letsencrypt.container.certs }}
              name: certbot-hostpathcerts
      hostname: certbot
      restartPolicy: Always
      volumes:
        - hostPath:
            path: {{ .Values.mounts.letsencrypt.host.root }}
            type: Directory
          name: certbot-hostpathroot
        - hostPath:
            path: {{ .Values.mounts.letsencrypt.host.certs }}
            type: Directory
          name: certbot-hostpathcerts
status: {}
