apiVersion: v1
kind: Service
metadata:
  labels:
    service: certbot
  name: certbot
spec:
  ports:
    - name: certbot
      port: 80
      targetPort: 80
      protocol: TCP
    - name: certbot-ssl
      port: 443
      targetPort: 443
      protocol: TCP
  selector:
    service: certbot
  type: ClusterIP

---

apiVersion: batch/v1
kind: CronJob
metadata:
  name: certbot
spec:
  schedule: "0 0 15 * *"
  successfulJobsHistoryLimit: 3
  failedJobsHistoryLimit: 1
  jobTemplate:
    spec:
      backoffLimit: 1
      completions: 1
      template:
        metadata:
          labels:
            service: certbot
        spec:
          containers:
            - image: certbot
              name: certbot
              imagePullPolicy: Never
              command:
                - /bin/sh
                - -c
                - certbot renew
              stdin: true
              tty: true
              ports:
                - name: web
                  containerPort: 80
                  protocol: TCP
              volumeMounts:
                - name: letsencrypt-vol
                  mountPath: /letsencrypt
                - name: letsencrypt-vol
                  mountPath: /etc/letsencrypt
                  subPath: certs
          hostname: certbot
          dnsConfig:
            options:
              - name: ndots
                value: "1"
          restartPolicy: Never
          volumes:
            - name: letsencrypt-vol
              persistentVolumeClaim:
                claimName: letsencrypt-pvc
          affinity:
            nodeAffinity:
              requiredDuringSchedulingIgnoredDuringExecution:
                nodeSelectorTerms:
                  - matchExpressions:
                      - key: kubernetes.io/hostname
                        operator: In
                        values:
                          - thinkpad
