apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: go-live
spec:
  ingress:
    - from:
      - podSelector:
          matchLabels:
            network/go-live: "true"
  podSelector:
    matchLabels:
      network/go-live: "true"
