apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  creationTimestamp: null
  name: go-live-default
spec:
  ingress:
    - from:
        - podSelector:
            matchLabels:
              network/go-live-default: "true"
  podSelector:
    matchLabels:
      network/go-live-default: "true"
