apiVersion: v1
kind: Service
metadata:
  labels:
    service: nginx-reverse-proxy
  name: nginx-reverse-proxy
spec:
  # type: LoadBalancer
  type: NodePort
  ports:
    - name: "443"
      port: 443
      targetPort: 443
      nodePort: 30111
    - name: "80"
      port: 80
      targetPort: 80
  selector:
    service: nginx-reverse-proxy
status:
  loadBalancer: {}
