apiVersion: v1
kind: Service
metadata:
  labels:
    service: waitress-flask-wsgi
  name: waitress-flask-wsgi
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    service: waitress-flask-wsgi
  type: ClusterIP

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: waitress-flask-wsgi
  name: waitress-flask-wsgi
spec:
  replicas: 2
  selector:
    matchLabels:
      service: waitress-flask-wsgi
  strategy: {}
  template:
    metadata:
      labels:
        service: waitress-flask-wsgi
    spec:
      containers:
        - image: waitress-flask-wsgi
          name: waitress-flask-wsgi
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources: {}
      hostname: waitress-flask-wsgi
      dnsConfig:
        options:
          - name: ndots
            value: "1"
      restartPolicy: Always
