apiVersion: v1
kind: Service
metadata:
  labels:
    service: waitress-flask-wsgi
  name: waitress-flask-wsgi
spec:
  ports:
    - name: "8000"
      port: 8000
      targetPort: 8000
  selector:
    service: waitress-flask-wsgi
status:
  loadBalancer: {}

---

apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    service: waitress-flask-wsgi
  name: waitress-flask-wsgi
spec:
  replicas: 2
  selector:
    matchLabels:
      service: waitress-flask-wsgi
  strategy: {}
  template:
    metadata:
      creationTimestamp: null
      labels:
        network/go-live-default: "true"
        service: waitress-flask-wsgi
    spec:
      containers:
        - image: waitress-flask-wsgi
          name: waitress-flask-wsgi
          imagePullPolicy: Never
          ports:
            - containerPort: 8000
          resources: {}
      hostname: waitress-flask-wsgi
      restartPolicy: Always
status: {}
