apiVersion: v1
kind: Pod
metadata:
  name: example-pod
  namespace: default
spec:
  containers:
  - name: volume-test
    image: nginx:stable-alpine
    imagePullPolicy: IfNotPresent
    volumeMounts:
    - name: example-pv
      mountPath: /data
    ports:
    - containerPort: 80
  volumes:
  - name: example-pv
    persistentVolumeClaim:
      claimName: local-path-pvc
