apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/rock/Documents/Thesaurus_Rex/docker_k8s/letsencrypt
        containerPath: /home/root/letsencrypt/
    extraPortMappings:
    - containerPort: 80
      hostPort: 80
      protocol: TCP
    - containerPort: 30111
      hostPort: 443
      protocol: TCP
