apiVersion: kind.x-k8s.io/v1alpha4
kind: Cluster
nodes:
  - role: control-plane
    extraMounts:
      - hostPath: /home/john/Documents/Thesaurus_Rex/docker/letsencrypt/
        containerPath: /home/john/Documents/Thesaurus_Rex/docker/letsencrypt/
