version: "3"
services:
  nginx-reverse-proxy:
    build: ./services/nginx-reverse-proxy
    hostname: nginx-reverse-proxy
    volumes:
      - ../letsencrypt:/letsencrypt
      - ../letsencrypt/certs:/etc/letsencrypt
    ports:
      - 443:443
      - 80:80
  waitress-flask-wsgi:
    build: ./services/waitress-flask-wsgi
    hostname: waitress-flask-wsgi
    expose:
      - 8000
  certbot:
    build: ./services/certbot
    hostname: certbot
    expose:
      - 9999  # for kompose
    volumes:
      - ../letsencrypt:/letsencrypt
      - ../letsencrypt/certs:/etc/letsencrypt
    stdin_open: true
    tty: true
